language: python
sudo: false
python:
  - 3.5
  - 2.7
cache: pip
install:
  - pip install -r requirements.txt
  - [ ${TRAVIS_PYTHON_VERSION} = "2.7" ] && pip install singledispatch
script:
  - "nosetests --with-coverage --cover-erase --cover-package=mongoengine_goodjson --all tests"
after_success:
  - coveralls
