language: python
python:
  - 3.5
addons:
  apt:
    packages:
      - "pandoc"
services:
  - "mongodb"
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python35.coverage"
  - "coveralls"
  - "pandoc --from=markdown --to=rst -o README.rst README.md"
deploy:
  provider: "pypi"
  user:
    secure: 'f6Yeb49GA0K3uqd8wM/K5fl3X3kOdbYuILw7TgF35vL4kVS8uCqOzmryavdbYH7tEt3VUNfK4aZ75vkwm+U0eAgPigzSuTPKg/N1q+ASip9H6cVTI3FYoVZXAv3HlNMObvnjLHn+/eVnVOKUkenFtAMModaeIGheXLLuGVGeAN6cOxTS6M/VawYzGcJ9TwRxjkwOYJoy1bZkd0HAEFK/CFKt/ZUhOjsOuBOZTpFB21PBlTzovVY4itHD+kENtgtlVb+pIDJBOFvn60FfE99nqdqh46hClLue6NYZqVCIZcYVbLBSnQ2w63MzjjNAexWNkPTwV3q7sLD/JgrPD5Y6uw3nTzrFTSYGpOdHa78EHckYNo1dRsirc+FqnDQerer0rotUTc/R1UG9kp3Bzlv8WEbeMcPAfVIeWbuOOzqChG3c1JH01je9QDBvN8gOJXZmw2vS0Fac6KZLf1HLy4fFCHDgsKBKnyuGKHsClepHSPM7mbiAzRoos7/L2Kj+XHUrD1hhSWpmZb3lVNYpunvBbtyB/ri4TuxxG1PQmZK9taVEG00VD1fOWFXYl40ImJ2Pl0i3lrnbi1gbEsR0syESu2K7sqejQYMswrRyzuWmDN6RQSck/em+22ppmG14pTPTb99jyzkwbaeWrvyFifbAD+7zoKlL47YYKlcnHxJB9xM='
  password:
    secure: "ujsgRTqYa1HPwh6zTsHAjWUKcShbrR22vwz6vgFKSC6hA/BNXLX6JMVs+l8l8o/w6JATYAbE8IMpmDtjGZ//R8A4Oq2j9lKurvfpcJNfiRxqKQh5E7xvCJ137RQpGcHvbB2CQVYUFD13N4lrKUeRNufgvyV+sMx7caljYKaQupSZEeLWaDY5hqeLmgOfWxo8JAqOWRTijAK04o+D41ZQlBgZi85HrP/UA/AckUpRA/kIdmLezXkGJHNL1339OhQbkYm2hZg+20Yt9rFmeVzGUF81zJWKyKPm3QTuu/POJRAo8Q3k2+1hFVn8/dfoTkwTqV+4mbTiLq+ajXLS3CATS3runrI84o4usqcBJO6s0O289S+qG/zZXy5jcV9ncTFXepIuAXq0522kU+XfP2adTjBzERJAmoSLR57gQ/9Kbo9QXuxu2uE3+CRwZE0QTSILP/8sR0+cKZmPycy5aKTRD7zyd/FDpfZrRD7HFPABEUlTBFrhahtff/CgwAm5l8YgEhuoNHB0ga3EzJESN29ZB+tVw8F0hU3yyKgpkJFqnl+XWg/VMLZOyCI6T6beIsdU4Up4DwzAEFDS34tLMPNb+at4FAXUNKDuJaKt+Ppa0ALFV7RO6lOe1db4r2wnUMdxFCm4/HfOW2tEuv7le6LxhtB3dxSrXmngF7yXuP7dxiU="
  on:
    tags: true
