language: python
python:
  - 3.5
services:
  - "mongodb"
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python35.coverage"
  - "coveralls"
