language: python
python:
  - 3.5
addons:
  apt:
    packages:
      - "pandoc"
services:
  - "mongodb"
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python35.coverage"
  - "coveralls"
  - "pandoc --from=markdown --to=rst -o README.rst README.md"
deploy:
  provider: "pypi"
  user:
    secure: 'f6Yeb49GA0K3uqd8wM/K5fl3X3kOdbYuILw7TgF35vL4kVS8uCqOzmryavdbYH7tEt3VUNfK4aZ75vkwm+U0eAgPigzSuTPKg/N1q+ASip9H6cVTI3FYoVZXAv3HlNMObvnjLHn+/eVnVOKUkenFtAMModaeIGheXLLuGVGeAN6cOxTS6M/VawYzGcJ9TwRxjkwOYJoy1bZkd0HAEFK/CFKt/ZUhOjsOuBOZTpFB21PBlTzovVY4itHD+kENtgtlVb+pIDJBOFvn60FfE99nqdqh46hClLue6NYZqVCIZcYVbLBSnQ2w63MzjjNAexWNkPTwV3q7sLD/JgrPD5Y6uw3nTzrFTSYGpOdHa78EHckYNo1dRsirc+FqnDQerer0rotUTc/R1UG9kp3Bzlv8WEbeMcPAfVIeWbuOOzqChG3c1JH01je9QDBvN8gOJXZmw2vS0Fac6KZLf1HLy4fFCHDgsKBKnyuGKHsClepHSPM7mbiAzRoos7/L2Kj+XHUrD1hhSWpmZb3lVNYpunvBbtyB/ri4TuxxG1PQmZK9taVEG00VD1fOWFXYl40ImJ2Pl0i3lrnbi1gbEsR0syESu2K7sqejQYMswrRyzuWmDN6RQSck/em+22ppmG14pTPTb99jyzkwbaeWrvyFifbAD+7zoKlL47YYKlcnHxJB9xM='
  password:
    secure: 'q59VdP0Lqq8ib0jZ/d0Wp2Jb/RpLYhoV8WMfo9hcsFUUnAFb+rp6lGCUxDW85nWDhQ9Bl3Cf+p3cR11rtiDKC66HAvrvyG0jqK+azlSam+uqVIfngwy05FsM09TMZOHcqDSwKlqg+BOTKYkqK0hnUpOH1atbW/YQm5X6zsqolBla9Pwba6JYF7w0mpmQQmNOKy/dHN0WCI3rnlFJDV393dc8+HdikK9Zc9kLqTm3HVsxH/9VYCzXQkov9We0TdMlj4kUqkSLq2iRsX3QF59mWgbBDfRG0EXauEjTGZRhOfedFIVGHpLCl+ddkGciW+2wIXmdzMSuDvS0fnlKmgspSGzU7H+IWPxoDRgeNwlpthmVX34ngg9CkHmEOcKHkzi72p1QwUyKtLN0MaK12zkElYdc6V/haszIfOzUnap/8LF9KnG4RoMzc7vsO/qowgrhD7EPkjov0Ugt3+R3AxjpBZlcJhGnYu98a7ifYxOglAkIHvluzNbP8kKu8MtHwdoGMsSsixw2I3SSJMWU2h+F4JXe6zjSl0Q9iAKvmeiPb6Zrz14A3nRkfpLnnNUCQpVHJn9NMktHDlH2VKj0vBH08qPNr/z+GxFdbc8nglbNzg+Itr+eD79Vra8FvqGKmBfgZfQpWqPzgHy3/W48+WcvB2DM4IFrDF2cpIKAtCoDIFo='
  on:
    tags: true
