language: python
python:
  - 3.6
sudo: false
cache: "pip"
addons:
  apt:
    packages:
      - pandoc
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python36.coverage"
  - "coveralls"
before_deploy:
  - "pandoc -f markdown -t rst -o README.rst README.md"
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist
  on:
    tags: true
    python: 3.6
  user:
    secure: >-
      gI74GkBa26PaoXwMiYB0pSj9+B6LydY0bixIRQn6qqjSVrDYv9stDqILhlJ2lhHqOLOkg93o
      8b5EqY4qZXAL2fllLw9SJFR/5LqFZQmR6SQIHoJPmLIJ57MLrYHn6OGI28aBnTms7zGkEnQc
      xaoT3X17Q/kpHI0U/s5vt6dhoWqYPPBZH6QdNBNx5of9FTjTT3O0vFN0E6EjqaeiirDyL1el
      7aLQxgqWdKdq73ECjsn6/MZgTDwcGYDk0qGfNmDOLdPk9ZE9qwRXgw5c7vPY7QWU8Zl7pGPt
      zI8YO+TtLJuDd1NuYdKfhjdmQcTwdDxeFoBfhTtDIKT4i2vNBiY1mBVQFvqwhLmBnVJfO1TU
      gCPJOOwS9RqOtXeKSC4YDcZzR1upekDkWviKFMcrDqR7yNA3GKv7jFfECdDlusgfnLk5wjsX
      hmLtgeq2lU0r2BRU/vcibuehCKjST3GiddiCjdU+dZYZZpvEewwlTxwGMIB58kP79ZwcnF6L
      G7dAhWfKA1+EvIlgRCzJMBOYE0F4I3uS02PxpVnkj9EiUMPjOccCP0KOBmiF7bj7gGnR7MN1
      VXSDrw+UmyZWt1DvVsNmsb97lF/bF6QqQ6xqsPhY+KSjCTy4y2vaYpeVkyfM9FjXudYtkIsD
      EFcJhVKvoWjVnf+IhhGGJsMA3jjllooiILI=
  password:
    secure: >-
      e8nWJP5YdkYY/qSHCDQbKMhlWvA/oLZ/dF9Yf5+zNYura05ZteX6+fq92fNS0ATRytzWqmKu
      k2vWXKG6eg/crbXgikxqTDuD/Q14bbMbOaR1nDudE+eYa7oTDgx+K7HiuNdmBjSYjroS1MO4
      FB+yTJrmPBlv3So5F3qELtk2qnTMoBGgbKb2Px09kIdPuaK5BxO4Ho8Bs0YFCBu6zka4sfh2
      5hJa6XOpiV0Ti8Vp3/N2X6aNrjKeBsNkQpDJcU17Q8eg1PMQPjr1ZWvgKqqdJc4mWlmc/Ob9
      ElcqZ4wWVjWl7rtzgIYZd1MfnexOJcgtrM5+JJwROZyetN9/IJrqXVPGlCrlKpRYPrDZDxMC
      YQVljDTzHME5Xaa2J2gCvTI/GYVYwWoXuIXU5lEUMqlGxGS/t5tewsscT1DCpd/24VVwiFJj
      49yuUeroryG3lpl1L8/wrC/0hyjaupNETsNYKXjnbCPmq5JyKJABHpPAKOyUci97FBu5zDR4
      8By44CmDvJOffGnxPFRQ5LdfJk1dnRr7SqPV4LnPwJu7m90tJn4TWpLTPY8qCIjDHdD/gz7s
      SOoi4Zg1+59fgbycjnJItMxymsKesh7l7J3rMkMoeBIPgRCHOPJAixjWQa4OpcDhXUyh26li
      ws6MI5e7ESigthN4ksS+LAFWP2jxOdxU+oE=
