language: python
sudo: false
python:
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 2.7
cache: pip
install:
  - pip install -r requirements.txt
  - if [ "${TRAVIS_PYTHON_VERSION}" = "2.7" -o  "${TRAVIS_PYTHON_VERSION}" = "3.2" -o "${TRAVIS_PYTHON_VERSION}" = "3.3"]; then pip install singledispatch; fi
script:
  - "nosetests --with-coverage --cover-erase --cover-package=mongoengine_goodjson --all tests"
after_success:
  - coveralls
