language: python
python:
  - 3.5
addons:
  apt:
    packages:
      - "pandoc"
services:
  - "mongodb"
sudo: false
cache: "pip"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 mongoengine_goodjson tests"
  - "radon cc -nc mongoengine_goodjson"
  - "tox"
after_success:
  - "coverage combine python27.coverage python35.coverage"
  - "coveralls"
  - "pandoc --from=markdown --to=rst -o README.rst README.md"
deploy:
  provider: "pypi"
  user:
    secure: "f6Yeb49GA0K3uqd8wM/K5fl3X3kOdbYuILw7TgF35vL4kVS8uCqOzmryavdbYH7tEt3VUNfK4aZ75vkwm+U0eAgPigzSuTPKg/N1q+ASip9H6cVTI3FYoVZXAv3HlNMObvnjLHn+/eVnVOKUkenFtAMModaeIGheXLLuGVGeAN6cOxTS6M/VawYzGcJ9TwRxjkwOYJoy1bZkd0HAEFK/CFKt/ZUhOjsOuBOZTpFB21PBlTzovVY4itHD+kENtgtlVb+pIDJBOFvn60FfE99nqdqh46hClLue6NYZqVCIZcYVbLBSnQ2w63MzjjNAexWNkPTwV3q7sLD/JgrPD5Y6uw3nTzrFTSYGpOdHa78EHckYNo1dRsirc+FqnDQerer0rotUTc/R1UG9kp3Bzlv8WEbeMcPAfVIeWbuOOzqChG3c1JH01je9QDBvN8gOJXZmw2vS0Fac6KZLf1HLy4fFCHDgsKBKnyuGKHsClepHSPM7mbiAzRoos7/L2Kj+XHUrD1hhSWpmZb3lVNYpunvBbtyB/ri4TuxxG1PQmZK9taVEG00VD1fOWFXYl40ImJ2Pl0i3lrnbi1gbEsR0syESu2K7sqejQYMswrRyzuWmDN6RQSck/em+22ppmG14pTPTb99jyzkwbaeWrvyFifbAD+7zoKlL47YYKlcnHxJB9xM="
  password:
    secure: "YE/ky30wGiMThHUQmSHGPznJ89/vKw9t1FogHW5tt1hLCPlGRxYic6F1QUzQ+QDA9N9K0cQb7E0TxtjjLdYvB8Ak4NdPY4E8OL+uMdH5uQpav07H2OPBMPLX1lcJUMCUSb1Vp43HcomZiUAmWj9nBrVk8d788OU1fpXuMIvVc6/6MXYVFPSNc+pFO4q8+QXgd8AEZDNLgIdVQkwi3zfp7vTxX3DhW0/62nssS5u6GHHPTxcR5CZYrMfSbLxyboF63Ra+hn1lfle0uJm0XJk5DR5pt2uLxYrksI1S57vP31RUYobPr5mb7ABbBQteIoVSYBkX9vwl0bdSRnyKaV8oULWLcXCg5F+Bk8fe3p64+AjWyCgIwsX946FOW65N4CcT4BsTbDFpXLZQezfJOEcduoE8qZ0giQtkVvCNHh4xjKu8pjFYXKXXLYJH0SpjjnskKVdYypgSCfyPXLn7jTdLeoo+dhfyHoMqQfs/2YaoQJOE5XBAx9TjStp3XrUqqnD0EV74rWBCnLgl85vN5PCuoC0gqaplhfI7g+A2Ye0KIOd3lT2fhwtTMxgtfmF1uu+X3KN45QLUF43wAbl4Th+RKHjPQtn/BCYk/iWyQAFpywjxFuWtlnVmXiiwHmI5Ld75DPnuvZIKdiAq1OqTeaJWz7+0P9u2kLj8aytnLTe4ubo="
  on:
    repo: "hiroaki-yamamoto/mongoengine-goodjson"
    tags: true
